In [1]:
import pandas as pd

In [40]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

In [3]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [9]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [ ]:
coffee.sample(10)

          Day Coffee Type  Units Sold
3     Tuesday       Latte          20
7    Thursday       Latte          30
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
10   Saturday    Espresso          45
4   Wednesday    Espresso          35
1      Monday       Latte          15
12     Sunday    Espresso          45
0      Monday    Espresso          25
13     Sunday       Latte          35

In [20]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [19]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [25]:
coffee.loc[0:3]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30
3  Tuesday       Latte          20

In [29]:
coffee.loc[:, ["Day", "Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [32]:
coffee.iloc[0:5, [0,2]]

         Day  Units Sold
0     Monday          25
1     Monday          15
2    Tuesday          30
3    Tuesday          20
4  Wednesday          35

In [ ]:
#coffee.index = coffee["Day"]

In [ ]:
#coffee.loc["Monday":"Wednesday", "Units Sold"]

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

coffee.iloc[Rows, Columns]  only using index values

In [37]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
#coffee.loc[1, "Units Sold"] = 10

In [39]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [42]:
coffee.at[0, "Units Sold"] #only single values

np.int64(25)

In [ ]:
coffee.iat[0,0] #also single

'Monday'

In [46]:
coffee.Day #if it is a single world or coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: str

In [55]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=False)  #sorts for first value if two units have the same
#value then it sorts by second value

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
7    Thursday       Latte          30
2     Tuesday    Espresso          30
5   Wednesday       Latte          25
0      Monday    Espresso          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [60]:
for index, row in coffee.iterrows():
    print(index)
    print(row['Units Sold'])
    print("\n\n")

#lose performance and should be used very rarely

0
25



1
15



2
30



3
20



4
35



5
25



6
40



7
30



8
45



9
35



10
45



11
35



12
45



13
35